"""rename department

Revision ID: 8165a03748f1
Revises: b1f4c5cc947c
Create Date: 2025-03-26 12:41:11.693522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8165a03748f1'
down_revision = 'b1f4c5cc947c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')

    # ### end Alembic commands ###
